spring.application.name=MySecretVault
spring.datasource.url=jdbc:postgresql://ep-wild-river-a1x22n9j-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.username=neondb_owner
spring.datasource.password=npg_cfRk1CAzbpm8
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.auto-commit=false


