spring.application.name=MySecretVault
spring.datasource.url=jdbc:postgresql://ep-wild-river-a1x22n9j-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.url=jdbc:postgresql://localhost:5432/MyVault
#spring.datasource.username=postgres
#spring.datasource.password=1289
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.auto-commit=false
server.port=${PORT:8080}

